### ISSUE TITLE
Create AE test data to include AELAT

### ISSUE THREAD

**Issue by barnett11** [pharmaverse/admiralophtha#12]
### Background Information

AELAT to denote standards "LEFT"/"RIGHT" - "BOTH"?

**Comment by ritika-aggarr** [comment]
Hi @barnett11 

Pushed AE test data and program under 12_create_AE_test_data@devel

As AELAT is collected on CRF, standard values are assigned randomly to AELAT when AESOC is "EYE DISORDERS". Could you please if that's okay?

Thanks!

**Comment by manciniedoardo** [comment]
Hi @ritika-aggarr  - I can confirm it's OK to assign standard values randomly for this test data. In order to align with the way test data is done on admiral.test, please could I ask that you:

- rename the script creating the ae test data to just `ae.R`
- make a dev folder at the top level of the repo and put the `oe.R` file in there
- add the following line to the .Rbuildignore file at the top level of the repo: ^dev$. This will ensure that the dev folder is ignored when the package is built, which is good because the test data scripts shouldn't be user-facing. Also the auto-check in the pull request don't like the dev folder being there, so this escapes that problem.
-at the bottom of your `ae.R` program, save it in a top-level folder called `data` as an RDS file rather than an RDA file (check how this is done in the EX test data branch if unsure.

Any qs please reach out.

Edo
