### ISSUE TITLE
Create OE test data

### ISSUE THREAD

**Issue by barnett11** [pharmaverse/admiralophtha#13]
### Background Information

Need a range of OE tests. Must include BCVA overall score

**Comment by barnett11** [comment]
https://github.com/pharmaverse/admiral.test/blob/main/dev/tr.R example test data

**Comment by aliceBIU** [comment]
> https://github.com/pharmaverse/admiral.test/blob/main/dev/tr.R example test data

Thanks @barnett11 !

**Comment by traceyxw** [comment]
Shall we include IOP data in the OE test data so that the test data can be used for testing the IOP function to be created #28 ?

**Comment by manciniedoardo** [comment]
Hi @aliceBIU I also have a request: please could you include the vars `OETPT` and `OETPTNUM`?  These are to be used to create `ATPT` and `ATPTNUM` in `ADOE`.

**Comment by aliceBIU** [comment]
@traceyxw @manciniedoardo no problem. will add and push to the repository later.

**Comment by manciniedoardo** [comment]
@aliceBIU thanks for adding the variables. I tried going into your branch and running your code to give it a quick QC, but I get an error with the `labelled`  and `metatools` packages. I think that's because they're not in the `renv.lock` file and also the imported functions from those packages are not in the `admiralophta-package.R` file. Please could you try update this so that I can run your code?

**Comment by manciniedoardo** [comment]
Also may be good to add iop test data to OE as well

**Comment by aliceBIU** [comment]
@manciniedoardo IOP data has already been added. Please take a look at the data stored in /data/admiral_oe.rda under my branch. I'll try to figure out the package dependency trick later so that labelled can be loaded. I've created a pull request to merge into devel but no one has reviewed it. Do I need to assign a reviewer? Thanks.

**Comment by wholmes57** [comment]
@aliceBIU I've added CST as a parameter. Specifically I've added the OESCAT of "SD-OCT CST SINGLE FORM". 

One quick question with regard to the BCVA score: where is the OETESTCD = "VACSCORE" coming from here? I've checked a few different previous datasets and I can only find "LOGSCORE"?

**Comment by manciniedoardo** [comment]
Hi @aliceBIU @wholmes57, in order to align with the way test data is done on admiral.test, please could I ask that you:

- rename the script creating the oe test data to just `oe.R`
- make a `dev` folder at the top level of the repo and put the `oe.R` file in there
- add the following line to the `.Rbuildignore` file at the top level of the repo: `^dev$`. This will ensure that the dev folder is ignored when the package is built, which is good because the test data scripts shouldn't be user-facing. Also the auto-check in the pull request don't like the `dev` folder being there, so this escapes that problem.

any qs please reach out.

Edo

**Comment by aliceBIU** [comment]
@wholmes57 It comes from the CRF page "BCVA Scores" (D. Visual acuity score = A + B + C =). And the mapping rules of this form can be found here [https://gdsr.roche.com/ui/gdsr-browser-app%23GDSRBrowser#/default/http%3A%2F%2Fgdsr.roche.com%2Fui%2Fws%2Fdata-collection-ui%23NavigationScheme.DataCollection/view/http%3A%2F%2Fgdsr.roche.com%2Fpd-biometrics%2Fecrf%23Form.Ophthalmology.BCV7/gdsr.roche.com]

I went through the adoe program of two reference studies and it seems the paramcd=BCVA records come from this sdtm testcd. Please let me know if that's incorrect or not generalizable.

**Comment by aliceBIU** [comment]
@wholmes57 It comes from the CRF page "BCVA Scores" (D. Visual acuity score = A + B + C =). And the mapping rules of this form can be found here [https://gdsr.roche.com/ui/gdsr-browser-app%23GDSRBrowser#/default/http%3A%2F%2Fgdsr.roche.com%2Fui%2Fws%2Fdata-collection-ui%23NavigationScheme.DataCollection/view/http%3A%2F%2Fgdsr.roche.com%2Fpd-biometrics%2Fecrf%23Form.Ophthalmology.BCV7/gdsr.roche.com]

I went through the adoe program of two reference studies and it seems the paramcd=BCVA records come from this sdtm testcd. Please let me know if that's incorrect or not generalizable.

**Comment by aliceBIU** [comment]
@manciniedoardo Thanks for the reminder! updated.

**Comment by wholmes57** [comment]
@aliceBIU Thanks for sharing the GDSR link. My confusion came from the fact that I can see that both VACSCORE and LOGSCORE have been used in some of our studies. Happy to stick with VACSCORE as you suggested.
