### ISSUE TITLE
General Issue: Lintr check failing on CRAN

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiralophtha#196]
### Background Information

See [here](https://github.com/r-lib/lintr/pull/2189).

### Definition of Done

Identify what went wrong and fix it.

**Comment by MichaelChirico** [comment]
Just install current `main` branch of {lintr} and run your tests -- if nothing's broken there's no need to do anything further. https://github.com/r-lib/lintr/pull/2189 is just reporting the results of `revdepcheck::revdep_check()` -- because of a possibly transient issue on CRAN, the check couldn't complete for {admiralophtha}, hence `NA` results.

I tried to install {admiralophtha} and run tests with dev {lintr} but ran into #200.
