### ISSUE TITLE
General Issue: ADOE Research

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiralophtha#42]
### Background Information

Look through the ADOE datasets on ophthalmology studies to which you have access. Please leave comment(s) here detailing ophthalmology-related:
- common derivations (that maybe take a lot of repetitive code)
- custom macros
- common variable derivations
- common endpoint derivations
- common derived parameters

Aim is to find out what functions/code we can provide in `{admiralophtha}` to streamline the production of an ADOE dataset in R. Then we can make issues for each piece of programming work and start implementing it!

**Comment by wholmes57** [comment]
Within the ADOE datasets that also contain BCVA parameters, it appears common to have many analysis criterion flags relating to the gain or loss of a given number of BCVA letters. Examples include:

_- Avoiding a Loss of >= 0 Letters in BCVA
- Gaining >= 0 Letters in BCVA
- Avoiding a Loss of >= 5 Letters in BCVA
- Gaining >= 5 Letters in BCVA
- etc. up to ~30 letters_

These directly relate to common secondary endpoints such as:
- Proportion of patients gaining >= 15, >= 10, >= 5, or >= 0 letters in BCVA from baseline over time
- Proportion of patients avoiding loss of >= 15, >= 10, >= 5, or >= 0 letters in BCVA from baseline over time

Other analysis criterions include (these also relate to secondary endpoints):

_- BCVA >= 69 Letters (20/40 or Better)
- BCVA <= 38 Letters (20/200 or Worse)
- Gaining >= 15 letters or achieving BCVA >= 84 letters_

I would have thought that we can implement a fairly simple function to calculate all of these.

**Comment by palmenl** [comment]
Hi @wholmes57 we have developed a function to derive AFEYE which can be used for ADOE and other datasets

**Comment by wholmes57** [comment]
@palmenl Thanks Lucy - thought that might have been the case!

**Comment by aliceBIU** [comment]
Apologies, guys! Been busy with a study and didn't have time to research on this. @wholmes57 I think the two ideas you brought up are great but I also saw the conversation you had with Edoardo. I'm actually not sure what the differences between ADOE and ADBCVA are (I missed the team discussion last week :(). Maybe we should make that clear first?

Anyway, based on two of the ophthalmology studies I've worked on, I'd like to share some ideas here:
1. We created an invalid BCVA flag to identify invalid BCVA records and I think that might be generalizable. Although the criteria may differ from study to study but we're still able to provide a function with all the common criteria available and let the user choose which criteria to include and also make it flexible to allow the user to add criteria. 

2. The two studies implemented the Estimand framework so that we created an intercurrent event dataset (ADICE) and had a function to get the censoring dates from ADICE and a set of analysis flags (ANLxxFL) to flag out records needed for different estimands (e.g. one for primary estimand, one for hypothetical strategy). But I remember the team wants to set estimand aside and standardize other things first?

3. LOCF was used to impute missing values in these studies and I believe we need a function to conduct LOCF? It's a common derivation type and widely used in ophtha studies (do we already have one in admiral?)

**Comment by aliceBIU** [comment]
Please feel free to reach out and discuss!
p.s. I have some ADOE R code in hand but need to check with the MMRM SME group if it's ok to share the code.

**Comment by manciniedoardo** [comment]
> 3. LOCF was used to impute missing values in these studies and I believe we need a function to conduct LOCF? It's a common derivation type and widely used in ophtha studies (do we already have one in admiral?)

There is a function being developed, see [here](https://github.com/pharmaverse/admiral/pull/1571). Do you think it would be sufficient for our needs?

**Comment by wholmes57** [comment]
Thanks @aliceBIU. I like your idea to implement the "invalid BCVA flag" - I agree that this should be useful for most studies.

As per your comments on estimands: I totally agree that we should be implementing this into strategy going forward. All new ophthalmology studies should be implementing estimands going forward. I mentioned this a while ago and I think the decision was to wait for `admiral` to complete this in the main package. I haven't looked into the progress here, but perhaps that's something we should follow-up on.

**Comment by palmenl** [comment]
Similar to the CRITxFL there is examples of Change from Baseline Category variable, mainly for BCVA. This could use the derive_var_chg() admiral function with some adjustments made
