### ISSUE TITLE
General Issue: ADBCVA Research

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiralophtha#44]
### Background Information

Look through the ADBCVA datasets on ophthalmology studies to which you have access. Please leave comment(s) here detailing ophthalmology-related:
- common derivations (that maybe take a lot of repetitive code)
- custom macros
- common variable derivations
- common endpoint derivations
- common derived parameters

Aim is to find out what functions/code we can provide in `{admiralophtha}` to streamline the production of an ADBCVA dataset in R. Then we can make issues for each piece of programming work and start implementing it!

**Comment by wholmes57** [comment]
@manciniedoardo Just seen your comment above - I've written a very similar thing in the ADOE thread!

Going back to last week's conversation on ADBCVA vs. ADOE, I've seen a couple of different approaches in our Phase 3s:

- I've seen the individual components of the combined overall BCVA score (such as the 1m test, the 4m test etc) as part of the ADOE dataset, but then the combined overall BCVA score is in a separate dataset ADBCVA
- I've also seen the combined overall BCVA score within the ADOE dataset and the individual components do not appear to be available anyway; ADBCVA does not exist

Given the fundamental importance of BCVA data, I think we should look to standardise this. Personally it seems logical to me to have _all_ BCVA data in either ADOE or ADBCVA, rather than split across the two datasets.

**Comment by manciniedoardo** [comment]
@wholmes57 I agree, although as discussed in last week's call all we can do is provide a template showing how we would map the data, and then provide the tools to program the ADaM datasets accordingly. If study teams want to do it differently (eg, use an ADOE dataset froe everything) then our tools should still allow that.

**Comment by manciniedoardo** [comment]
I have seen across a couple of different Roche ADBCVA programs that there are lines of code dedicated to converting ETDRS scores to LogMAR scores. The conversion is a one-liner: 
```
logMAR = -0.02 * ETDRS + 1.7
```
but it might be worth making a utility function `etdrs_to_logmar` that implement it, so that we could do something like:
```
ABCVA <- ADBCVA %>%
  mutate(AVAL = ifelse(<select ETDRS records only>, etdrs_to_logmar(OESTRESN), OESTRESN)
```
or maybe:
```
ABCVA <- ADBCVA %>%
  etdrs_to_logmar(<selection criteria for ETDRS records only>)
```
and possibly an inverse `logmar_to_etdrs` function? I think the first option is more attractive and, although quite simple, increases the transparency of the program 

In general, this is quite  a simple concept, but still valuable in my opinion: rather than just seeing a formula, you encode it in a function but describe what the function is doing.
